support py37-39, dj32, drop dj11, py27
beproud/bpcommons pull request #28
Opened 2022-01-03 09:38 UTC by cactusman-bp

2022-01-04 03:40 UTC, aodag commented
> Python3.10を対応にいれていないのは、distutilsが非推奨になってるためです。

使ってるように見えないですが、ブロッカーになってるのでしょうか？

2022-01-04 08:20 UTC, shimizukawa requested changes
MUST, SHOULD あります。
Python-3.10 サポートしてよさそうに思います。

2022-01-04 08:20 UTC, shimizukawa commented on ChangeLog.rst
> +==========================
MUST: 0.42の記述は不要。0.41のリリース時にPyPIにこれも表示されてしまうため。

2022-01-04 08:20 UTC, shimizukawa commented on setup.py
> +        'Framework :: Django :: 3.2',
MUST: 数行したのPythonのサポートバージョンも更新お願いします。

2022-01-04 08:20 UTC, shimizukawa commented on ChangeLog.rst
> +- Support Python-3.7, 3.8, 3.9, 3.10
ASK: 3.10 はサポート対象なのか、対象外なのか？

2022-01-04 08:20 UTC, shimizukawa commented on ChangeLog.rst
> +- Update BeautifulSoup4-4.10 (from 4.6)
MUST: BeautifulSoupのバージョンはリリース情報に不要。

4.10はテスト用に固定しているだけで、setup.pyのinstall_requiresで依存はしていない。
リリース情報として出す必要はないはず。

2022-01-04 08:20 UTC, shimizukawa commented on ChangeLog.rst
> +- Drop Python-2.7
MUST: この行は不要。

Python-2.7は Release 0.39でドロップ済み

2022-01-04 08:20 UTC, shimizukawa commented on tests/settings.py
> +USE_TZ = False
ASK: 何のため？

2022-01-04 08:20 UTC, shimizukawa commented on tests/testapp/views.py
> +            re_path(
SHOULD: 正規表現によるパス記法ではなく、 `path` を使って新し記法に変更したほうがよさそう。

```
path('test', ...)
```

2022-01-04 08:20 UTC, shimizukawa commented on tests/testapp/urls.py
> +    re_path(r'', include(TestViews().urls)),
SHOULD: `path` で良さそう

2022-01-06 06:13 UTC, cactusman-bp commented on tests/testapp/views.py
> +            re_path(
修正します。

2022-01-06 06:13 UTC, cactusman-bp commented on tests/testapp/urls.py
> +    re_path(r'', include(TestViews().urls)),
修正します。

2022-01-06 06:13 UTC, cactusman-bp commented on tests/settings.py
> +USE_TZ = False
いろいろやってた名残なので、消します。

2022-01-06 06:13 UTC, cactusman-bp commented on ChangeLog.rst
> +- Drop Python-2.7
消します。

2022-01-06 06:13 UTC, cactusman-bp commented on ChangeLog.rst
> +==========================
消します。

2022-01-06 06:13 UTC, cactusman-bp commented on ChangeLog.rst
> +- Update BeautifulSoup4-4.10 (from 4.6)
消します。

2022-01-06 06:15 UTC, cactusman-bp commented on setup.py
> +        'Framework :: Django :: 3.2',
追加します。

2022-01-06 06:17 UTC, cactusman-bp commented
Python3.10について、toxでの実行結果(Django2.2でも同様のエラー)


```
py310-dj32 installdeps: pytest, pytest-django, factory-boy, BeautifulSoup4==4.10.0, mock, Django>=3.2,<4.0
ERROR: invocation failed (exit code 1), logfile: /workspaces/bpcommons/.tox/py310-dj32/log/py310-dj32-1.log
==================================================================================================================================================================================== log start =====================================================================================================================================================================================
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 13, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 40, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/workspaces/bpcommons/.tox/py310-dj32/lib/python3.10/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

2022-01-06 08:22 UTC, shimizukawa commented
> pip のバージョンは21.3.1。

tox外のpipのバージョンが最新でも、toxのvirutalenv内が古いとそうなりそうですね。
@cactusman-bp tox.iniのdepsで明示的に "pip>=21.3" を指定するのがよさそうです。

2022-01-06 08:31 UTC, cactusman-bp commented
> tox.iniのdepsで明示的に "pip>=21.3" を指定するのがよさそうです。
やってみます。

2022-01-06 08:38 UTC, shimizukawa commented
@cactusman-bp 正確な書き方はこちら
https://tox.wiki/en/latest/config.html#conf-requires
```
[tox]
requires =
           pip >= 21.3
```

2022-01-24 05:21 UTC, cactusman-bp commented
github action上で、python 3.10でのテストが実行できるようにし、テストは通っている状態。

ただし、code space上ではtoxでpipのバージョン指定しても" ModuleNotFoundError: No module named 'distutils.cmd'
 " エラーになる。

2022-01-24 05:25 UTC, cactusman-bp commented on ChangeLog.rst
> +- Support Python-3.7, 3.8, 3.9, 3.10
github action上で確認できたので、3.10をサポート対象にしました。

2022-01-24 06:03 UTC, shimizukawa requested changes
MUSTあります

2022-01-24 06:03 UTC, shimizukawa commented on setup.py
> +        'Programming Language :: Python :: 3.9',
MSUT: ここも3.10が抜けています

2022-01-24 06:03 UTC, shimizukawa commented on tox.ini
> +    pip>=21.3
MAY: セクションとキーが違うかも

https://github.com/beproud/bpcommons/pull/28#issuecomment-1006377861
に書きましたが、以下ではないでしょうか？

```
[tox]
requires =
           pip >= 21.3
```

正確な書き方はこちら
https://tox.wiki/en/latest/config.html#conf-requires

2022-01-24 06:19 UTC, cactusman-bp commented on tox.ini
> +    pip>=21.3
指摘のように修正したものの、相変わらずエラー

2022-01-24 06:19 UTC, cactusman-bp commented on setup.py
> +        'Programming Language :: Python :: 3.9',
対応しました。

2022-01-24 06:19 UTC, cactusman-bp commented on README.rst
> +- Python: 3.6, 3.7, 3.8, 3.9, 3.10
対応しました。

2022-01-24 06:20 UTC, shimizukawa commented on tox.ini
> +    pip>=21.3
MUST: @cactusman-bp `[testenv]` セクションじゃないです。 `[tox]` セクションです

2022-01-24 06:31 UTC, cactusman-bp commented on tox.ini
> +    pip>=21.3
指摘通りに移動させたものの、相変わらずエラー。
ただ、修正は反映させています。

2022-01-24 07:21 UTC, cactusman-bp commented on tox.ini
> +    pip>=21.3
[tox] セクションに書くと、github actionの実行がおかしくなったので、requires の pip指定は削除しています。

2022-01-24 07:24 UTC, cactusman-bp commented on tox.ini
> +    py{36,37,38,39,310}-dj{22,32}
> requires = pip  >= 21.3

を入れると、github actionの実行がおかしくなったので、入れていないです。

2022-01-24 07:44 UTC, aodag commented
3.10でdistutilsが絡んだエラーが発生する場合は環境変数に `SETUPTOOLS_USE_DISTUTILS=stdlib` を追加してみてください。

https://twitter.com/jaraco/status/1467660250954317827?s=20

2022-01-25 01:41 UTC, cactusman-bp commented
3.10でdistutils のエラーについては、

> sudo apt install python3.10-distutils

で、別途3.10用のライブラリをインストールすることで、解消されました。

2022-01-25 02:44 UTC, shimizukawa approved these changes
LGTM

2022-01-25 02:45 UTC, merged

2022-01-25 02:46 UTC, shimizukawa commented
> リリース後のdj32ブランチはすぐに削除してほしくないです。(案件でpipインストール時に見ているので)